[project]
name = "basellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Supreme_Engineer98", email = "gmavropouloscoding@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
basellm = "basellm:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
